---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2019/4/16 10:46
---

require 'util.id'

local t = {
    1497654064, 1497654065, 1497654066, 1497654067, 1497654068, 1497654069,
    1497654070, 1497654071, 1497654072, 1497654073, 1497654113, 1497654114,
    1497654115,
}

for i, v in ipairs(t) do
    print(base.id2string(v))
end

local s = {
    'o00A'
}

for i, v in ipairs(s) do
    print(base.string2id(v))
end