---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2019/4/22 16:40
---

require 'kungfu.tiezhang.guiYuanTuNa'

local kungfu = {}

function kungfu.init()
    registerGuiYuan()
end


return kungfu