---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2019/4/22 14:08
---

local japi = require 'jass.japi'

local flag = not not japi.DzGetGameUI and CONFIG.USE_NEW_UI

if not flag then
    print('当前环境不支持暴雪API')
    return
end

UI = {}
ANCHOR = {
    TOPLEFT = 0,
    TOP = 1,
    TOPRIGHT = 2,
    LEFT = 3,
    CENTER = 4,
    RIGHT = 5,
    BOTTOMLEFT = 6,
    BOTTOM = 7,
    BOTTOMRIGHT = 8,
}
FRAME_EVENT = {
    NONE = 0,
    FRAME_EVENT_PRESSED = 1,
    FRAME_MOUSE_ENTER = 2,
    FRAME_MOUSE_LEAVE = 3,
    FRAME_MOUSE_UP = 4,
    FRAME_MOUSE_DOWN = 5,
    FRAME_MOUSE_WHEEL = 6,
    FRAME_FOCUS_ENTER = 2,
    FRAME_FOCUS_LEAVE = 3,
    FRAME_CHECKBOX_CHECKED = 7,
    FRAME_CHECKBOX_UNCHECKED = 8,
    FRAME_EDITBOX_TEXT_CHANGED = 9,
    FRAME_POPUPMENU_ITEM_CHANGE_START = 10,
    FRAME_POPUPMENU_ITEM_CHANGED = 11,
    FRAME_MOUSE_DOUBLECLICK = 12,
    FRAME_SPRITE_ANIM_UPDATE = 13,
}

local function initNewUi()
    japi.DzLoadToc( "ui\\custom.toc" )

    UI[100] = japi.DzCreateFrame("1", japi.DzGetGameUI(), 0)
    japi.DzFrameClearAllPoints( UI[100] )
    japi.DzFrameSetPoint( UI[100], 2, japi.DzGetGameUI(), 2, 0.00, -0.01 )
    japi.DzFrameSetSize( UI[100], 0.07, 0.02 )
    japi.DzFrameShow( UI[100], true )

    UI[99] = japi.DzCreateFrame("2", japi.DzGetGameUI(), 0)
    japi.DzFrameClearAllPoints( UI[99] )
    japi.DzFrameSetPoint( UI[99], 2, japi.DzGetGameUI(), 2, 0.00, -0.03 )
    japi.DzFrameSetSize( UI[99], 0.07, 0.02 )
    japi.DzFrameShow( UI[99], true )

    UI[98] = japi.DzCreateFrame("3", japi.DzGetGameUI(), 0)
    japi.DzFrameClearAllPoints( UI[98] )
    japi.DzFrameSetPoint( UI[98], 2, japi.DzGetGameUI(), 2, 0.00, -0.05 )
    japi.DzFrameSetSize( UI[98], 0.07, 0.03 )
    japi.DzFrameShow( UI[98], true )

    UI[97] = japi.DzCreateFrame("4", japi.DzGetGameUI(), 0)
    japi.DzFrameClearAllPoints( UI[97] )
    japi.DzFrameSetPoint( UI[97], ANCHOR.TOPLEFT, japi.DzGetGameUI(), ANCHOR.TOPLEFT, 0.10, 0.10 )
    japi.DzFrameSetSize( UI[97], 0.16, 0.16 )
    japi.DzFrameShow( UI[97], true )
end 

initNewUi()