---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2019/5/4 0004 9:56
---


--- 古董快速兑换书籍

local jass = require 'jass.common'
local bag = require 'util.collection.bag'
local stack = require 'util.collection.stack'
local g = require 'jass.globals'

local jianghu_bag = bag:new({ 'I053', 'I054', 'I055' })
local juexue_bag = bag:new({ 'I056', 'I057', 'I058' })
local juenei_bag = bag:new({ 'I059', 'I05A', 'I05B' })
local canzhang_bag = bag:new({ 'I05C', 'I05C' })

--- 兑换书籍
--- @param itemIdBag bag
--- @param itemTable table<string, stack>
--- @param bookBag bag
--- @param award number
--- @param x number 创建物品的X位置
--- @param y number 创建物品的Y位置
local function exchange(itemIdBag, itemTable, bookBag, award, x, y)
    if itemIdBag:containsAll(bookBag) then
        itemIdBag:removesAll(bookBag)
        for element, count in pairs(bookBag, defaultComp) do
            for i = 1, count do
                itemTable[element]:pop():remove()
            end
        end
        et.item:new(award, x, y)
    end
end

function exchangeBooks()
    --- @param u unit
    --- @param id string
    --- @param target unit|item|point
    et.game:event '单位-技能生效'(function(self, u, id, target)
        if id == 'A08O' then
            local x, y = target[1], target[2]
            local r = et.rect.new(x - 300, y - 300, x + 300, y + 300)
            local itemTable = {}
            local itemIdBag = bag:new()
            jass.EnumItemsInRect(r.handle, nil, function()
                local it = et.item:get(jass.GetEnumItem())
                local itemId = it:get_id()
                itemTable[itemId] = itemTable[itemId] or stack:new()
                itemTable[itemId]:push(it)
                itemIdBag:insert(itemId)
                exchange(itemIdBag, itemTable, jianghu_bag, g.udg_jianghu[jass.GetRandomInt(1, 18)], x, y)
                exchange(itemIdBag, itemTable, juexue_bag, g.udg_juexue[jass.GetRandomInt(1, 10)], x, y)
                exchange(itemIdBag, itemTable, juenei_bag, g.udg_juenei[jass.GetRandomInt(1, 8)], x, y)
                exchange(itemIdBag, itemTable, canzhang_bag, g.udg_canzhang[jass.GetRandomInt(1, 10)], x, y)
            end)
        end
    end)

end

