---
--- Generated by EmmyLua(https:--github.com/EmmyLua)
--- Created by G. Seinfeld.
--- DateTime: 2021/6/21 0021 15:09
---

require 'util.id'
local g = require 'jass.globals'

--- @param source unit 伤害来源
--- @param target unit 伤害目标
--- @param w1 number 伤害系数w1
--- @param w2 number 伤害系数w2
--- @param coeff number 伤害系数
--- @param id number|string 技能ID
local function damage_formula(source, target, w1, w2, coeff, id)
    local p = source:get_owner()
    local i = p:get() + 1
    local damage = 0

    local attack -- 伤害因子
    local target_def -- 目标防御因子
    local special_def -- 特殊防御因子
    local dodge -- 闪避因子
    local random -- 随机因子
    local basic_damage -- 基础伤害
    local str = source:get_str() -- 招式伤害
    local agi = source:get_agi() -- 内力
    local int = source:get_int() -- 真实伤害

    if source:is_hero() then
        attack = 1 + 0.3 * source:get_ability_level('A059')
                * 160
                * g.udg_lilianxishu[i]
                * (w1 * (1 + str / 300) * (1 + agi / 300) + w2 * 0.02 * int)
                * (1.5 + 0.5 * source:get_ability_level(id))
                * (1 + g.udg_shanghaijiacheng[i])
                * coeff

        if g.udg_yanglao then
            attack = attack * 30
        end

        if source:get_ability_level(id) == 9 then
            attack = attack * 3
        end

        if source:has_item('I0EE') then
            attack = attack * 3
        end

        local unit_id = source:get_type_id()
        if source:has_item('I099') and base.is_include(unit_id, { 'O000', 'O001', 'O004', 'O02J' }) then
            attack = attack * 1.5
        end
        if source:has_item('I09A') and base.is_include(unit_id, { 'O002', 'O003', 'O023', 'O02H', 'O02I' }) then
            attack = attack * 1.5
        end
    else
        attack = 750 * (w1 + w2) * (1 + source:get_ability_level(id)) * coeff
    end

    -- 敌方防御因子
    target_def = target and 1 / (1 + 0.1 * target:get_level()) or 1

    -- 特防
    if g.special_attack[i] >= 6 * (1 + g.udg_nandu) or target:has_ability('B022') then
        special_def = math.max(1 + (g.special_attack[i] - 6 * (1 + g.udg_nandu)) * 0.06, 1)
    else
        special_def = 1 / (1 + 0.06 * ((1 + g.udg_nandu) * 6 - g.special_attack[i]))
    end

    if not target then
        dodge = 25
    else
        dodge = math.min(target:get_level() / 5, 95)
        if (target:has_ability('Bslo')) then
            dodge = 0
        end
    end

    random = math.random(0.95, 0.95 + g.udg_xinggeB[i] / 20)
    basic_damage = attack * target_def * random * special_def

    -- 红怪
    if jass.LoadInteger(g.YDHT, jass.GetHandleId(target), jass.StringHash("color")) == 1 then
        basic_damage = basic_damage / 100
    end
    -- 绿怪
    if jass.LoadInteger(g.YDHT, jass.GetHandleId(target), jass.StringHash("color")) == 2 then
        basic_damage = basic_damage / 1000
    end
    -- 蓝怪
    if jass.LoadInteger(g.YDHT, jass.GetHandleId(target), jass.StringHash("color")) == 3 then
        basic_damage = basic_damage / 10000
    end

    -- 无尽BOSS战模式第N个BOSS
    if target == g.udg_boss[7] and g.tiaoZhanIndex == 3 then
        basic_damage = basic_damage / jass.Pow(10, g.endless_count)
    end

    -- 先天功不会miss
    if source:get_ability_level('A0CH') >= 1 then
        dodge = 0
    end

    if jass.GetRandomReal(0, 100) < dodge then
        damage = 0
    else
        damage = basic_damage
    end

    if type(id) == 'string' then
        id = base.string2id(id)
    end

    jass.SaveReal(jass.YDHT, i, id * 3, basic_damage)
    return damage
end

--- @param ability_id number|string 技能ID
--- @param source unit 伤害来源
--- @param target unit|table<number, unit> 伤害目标
--- @param action nil|function 伤害动作
--- @param effect function 特效 自己、敌人、地面
--- @param possibility number|function 触发概率
--- @param exclusive function 专属加成
--- @param damage_coefficients table<number, number> 伤害系数[w1, w2]
--- @param levelup_coefficients number 升重系数
--- @param combinations table<number, function> 搭配
local function passive_ability(ability_id, source, target, action, effect,
                               possibility, exclusive, damage_coefficients, levelup_coefficients, combinations)
    -- 技能ID
    if type(ability_id) == 'string' then
        ability_id = base.string2id(ability_id)
    end

    -- 触发概率
    local p = source:get_owner()
    local i = p:get() + 1
    if type(possibility) == 'function' then
        possibility = possibility(g.fuyuan[i])
    end
    -- 专属加成


    if source:has_ability(ability_id) and math.random(1, 100) <= possibility then
        -- 伤害动作
        if not action then
            -- 直接造成伤害

            if type(target) == 'table' then
                -- AOE
            else
                -- 单体
            end
        else
            -- 自定义，如马甲施放技能、召唤物等
            if type(action) == 'function' then
                action(source, target)
            end
        end

        -- 特效
        effect(source, target)

        -- 升重

    end

end

common_ability = common_ability or {}

common_ability.passive = function(config)
    local ability_id = config.ability_id
    local source = config.source ---@type unit
    local target = config.target
    local action = config.action -- 可选
    local effect_str = config.effect_str
    local effect_target = config.effect_target or 'target'
    local effect_attach = config.effect_attach or 'overhead'
    local effect_point = config.effect_point or source:get_point()
    local possibility = config.possibility or 20
    local exclusive = config.exclusive
    local damage_coefficients = config.damage_coefficients or { 10, 10 }
    local levelup_coefficients = config.levelup_coefficients or 1000
    local combinations = config.combinations

    local effect = function(us, ut)
        if effect_target == 'source' then
            et.effect.add_to_unit(effect_str, us, effect_attach):destroy()
        elseif effect_target == 'target' then
            if type(ut) == 'table' then
                for _, v in ipairs(ut) do
                    et.effect.add_to_unit(effect_str, v, effect_attach):destroy()
                end
            else
                et.effect.add_to_unit(effect_str, ut, effect_attach):destroy()
            end

        elseif effect_target == 'point' then
            et.effect.add_to_point(effect_point, effect_point)
        end
    end
    passive_ability(ability_id, source, target, action, effect,
            possibility, exclusive, damage_coefficients, levelup_coefficients, combinations)

end
