---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2019/4/22 16:27
---

local g = require 'jass.globals'
local rect = require 'entity.rect'

CONFIG = {
    USE_NEW_UI = false,
}

GLOBALS = {
    MAP_AREA = rect.j_rect(g.bj_mapInitialPlayableArea),
    JIANGHU_ITEMS = { 'I03J', 'I03H', 'I02V', 'I02U', 'I03G', 'I02Z', 'I03I', 'I02X', 'I02Y',
                      'I03K', 'I03D', 'I03L', 'I030', 'I031', 'I03E', 'I033', 'I02W', 'I03F', },
    JUEXUE_ITEMS = { 'I039', 'I034', 'I038', 'I037', 'I03B', 'I032', 'I035', 'I036', 'I03C', 'I03A', },
    JUENEI_ITEMS = { 'I03S', 'I03O', 'I03T', 'I03Q', 'I03M', 'I03P', 'I03U', 'I03R', },
    CANZHANG_ITEMS = { 'I065', 'I061', 'I066', 'I064', 'I067', 'I062', 'I069', 'I060', 'I068', 'I063', 'I0CW', },
    QIWU_ITEMS = { 'I0C2', 'I0C3', 'I0C4', 'I0C5', 'I0C6', 'I0C8', 'I0C9', 'I0CA', 'I0CB',
                   'I0CC', 'I0CD', 'I0CJ', 'I0CT', 'I0CU', 'I0CV', },
}