---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2019/4/24 14:43
---

require 'logic.globals'
require 'logic.recordHandleNumber'
require 'logic.mongolia_camp'
local jass = require 'jass.common'
local g = require 'jass.globals'

local logic = {}

function logic.init()
    initMongoliaCamp() -- 1.7之蒙古大营
    recordHandleNumber()
end

return logic
