---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2019/4/24 14:43
---

require 'logic.globals'
require 'logic.recordHandleNumber'

local logic = {}

function logic.init()
    recordHandleNumber()
end

return logic