---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2019/4/26 16:22
---

local npc = {
    suifeng = { name = '新手教官', loc = et.point(365, -692), adjust = { -50, 0 } },
    fengling1 = { name = '积分商店', loc = et.point(-1451.6, -1346), adjust = { -50, 0 } },
    fengling2 = { name = '道具商城', loc = et.point(-1268.9, -1365.7), adjust = { -50, 0 } },
    cangqiong = { name = '等级奖励', loc = et.point(-1396.8, -161.8), adjust = { -50, 0 } },
    yizhan = { name = '驿站', loc = et.point(-108.1, -1394.7), adjust = { -50, 0 } },
    gudong = { name = '古董商人', loc = et.point(670.9, -1270.5), adjust = { -50, 0 } },
    feini = { name = '练功木桩', loc = et.point(-35, -104), adjust = { -50, 0 } },
    fuben = { name = '副本传送', loc = et.point(-1321, -1888), adjust = { -50, 0 } },
    zeige = { name = '贼哥', loc = et.point(-1462, -470), adjust = { -50, 0 } },
    pingyizhi = { name = '炼制丹药', loc = et.point(-2032.3, -1442.2), adjust = { -50, 0 } },
    shipotian = { name = '历练传送', loc = et.point(-2081.6, -1962.8), adjust = { -50, 0 } },
    baoshi = { name = '宝石商人', loc = et.point(598.6, -2015.8), adjust = { -50, 0 } },
    guojing = { name = '选择副职', loc = et.point(-2053.7, -339.5), adjust = { -50, 0 } },
}

local function createHint(tab)
    local loc = tab.loc + tab.adjust
    et.tag.create(tab.name, loc, 13, 100, 100, 100, 0, 50)
end

function showNpcHint()
    for k, v in pairs(npc, defaultComp) do
        log.debug(k, v)
        createHint(v)
    end
end
