---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2019/5/10 11:19
---

local debug = require 'jass.debug'

--currentpos 当前jass执行到的位置
--handlemax jass虚拟机当前最大的handle
--handlecount jass虚拟机当前的handle数

function recordHandleNumber()
    et.loop(10 * 1000, function()
        --for k, v in pairs(debug) do
        --    print(k, v)
        --end
        --log.info('当前jass执行到的位置为：'..debug.currentpos())
        print('当前jass虚拟机最大的handle为：'..debug.handlemax())
        print('当前jass虚拟机的handle数为：'..debug.handlecount())
    end)
end