---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by G_Seinfeld.
--- DateTime: 2019/4/24 14:42
---

local g = require 'jass.globals'


local VIP = {
    "WorldEdit", "zeikale", "zeikala", "非我莫属xq", "苍穹而降", "晓窗临风", "沫Mu"
}

local TALENT_LOOKUP = {
    { name = '天纵奇才', level = 1, buff = 'B01O' }, -- 天纵奇才：增加升重速度
    { name = '天降鸿福', level = 2, buff = 'B01P' }, -- 天降鸿福：每2分钟增加1点福缘
    { name = '天赋异禀', level = 3, buff = 'B01S' }, -- 天赋异禀：每2分钟增加1点经脉
    { name = '醍醐灌顶', level = 4, buff = 'B01T' }, -- 醍醐灌顶：每2分钟增加1点悟性
    { name = '骨骼精奇', level = 5, buff = 'B01R' }, -- 骨骼精奇：每2分钟增加1点根骨
    { name = '飞来横财', level = 6, buff = 'B01Q' }, -- 飞来横财：每2分钟增加5000金钱和20珍稀币
    { name = '冲州过府', level = 7, buff = 'B01U' }, -- 冲州过府：增加每次杀怪获取的声望值
}

--- 增加天赋系统
--- @param i number 玩家下标
--- @param t number 天赋下标，见上面的查询表
local function add_talent(i, t)
    log.info(('为玩家%s增加天赋%s'):format(i, TALENT_LOOKUP[t].name))
    if (g.udg_hero[i] ~= nil) then
        --- @type unit
        local u = et.unit(g.udg_hero[i])
        u:add_ability('A08M')
        jass.SetPlayerAbilityAvailable(u:get_owner().handle, base.string2id('A08M'), false)
        u:set_ability_level('A08L', t)
        u:get_owner().talent = t
    end
end

function talent_effect()

    -- 判断玩家是否购买
    et.loop(1 * 1000, function()
        for i = 1, 5 do
            local p = et.player[i]
            --- 随机天赋
            if p:is_player() and p.talent == 0 and g.talent_flag[i] == 1 then
                add_talent(i, base.random_int(1, #TALENT_LOOKUP))
            end
        end
    end)

    --- @param p player
    --- @param s string
    et.game:event '玩家-聊天'(function(self, p, s)
        if s == 'testme2' and g.udg_isTest[p:get()-1] then
            local logger = function(text)
                log.info(text)
                p:send_message(text)
            end
            logger(('玩家名字为%s'):format(p:get_base_name()))
            logger(('hasMallItem是否存在：%s'):format(not not hasMallItem))
            logger(g.PROPERTY_TALENT)
            logger(g.PROPERTY_TIEZHANG)
        end
        if s:sub(1, 6) == 'enable' and g.udg_isTest[p:get()-1] then
            local id = s:sub(8, 11)
            jass.UnitMakeAbilityPermanent(g.udg_hero[1], true, base.string2id(id))
            jass.SetPlayerAbilityAvailable(p.handle, base.string2id(id), true)
            p:send_message(jass.GetObjectName(base.string2id(id))..'技能已启用')
        end
        if s:sub(1, 7) == 'disable' and g.udg_isTest[p:get()-1] then
            local id = s:sub(9, 12)
            jass.UnitMakeAbilityPermanent(g.udg_hero[1], true, base.string2id(id))
            jass.SetPlayerAbilityAvailable(p.handle, base.string2id(id), false)
            p:send_message(jass.GetObjectName(base.string2id(id))..'技能已禁用')
        end
        if jass.StringHash(s) == 1661513981 then
            g.testVersion = true
            g.udg_isTest[p:get()-1] = true
        end
        if base.is_include(p:get_base_name(), VIP)  and not g.udg_isTest[p:get()-1] then
            g.udg_isTest[p:get()-1] = true
        end
        if g.udg_isTest[p:get()-1] and g.talent_flag[p:get()] == 0 then
            local i = p:get()
            g.talent_flag[i] = 1
            g.tiezhang_flag[i] = 1
            g.tangmen_flag[i] = 1
            g.mall_addition[i] = 1
            g.level_award[i] = 1
            p:send_message("开启了天赋、铁掌帮和唐门的权限，开启双倍积分和萌新礼包权限")
        end
    end)

    et.loop(120 * 1000, function()
        for i = 1, 5 do
            local p = et.player[i]
            -- 天降鸿福：每2分钟增加1点福缘
            if p.talent == 2 then
                g.fuyuan[i] = g.fuyuan[i] + 1 + (g.bigTalent[i] or 0)
                -- 天赋异禀：每2分钟增加1点经脉
            elseif p.talent == 3 then
                g.jingmai[i] = g.jingmai[i] + 1 + (g.bigTalent[i] or 0)
                --  醍醐灌顶：每2分钟增加1点悟性
            elseif p.talent == 4 then
                g.wuxing[i] = g.wuxing[i] + 1 + (g.bigTalent[i] or 0)
                -- 骨骼精奇：每2分钟增加1点根骨
            elseif p.talent == 5 then
                g.gengu[i] = g.gengu[i] + 1 + (g.bigTalent[i] or 0)
                -- 飞来横财：每2分钟增加5000金钱和20珍稀币
            elseif p.talent == 6 then
                p:add_gold(5000 + 5000 * (g.bigTalent[i] or 0))
                p:add_lumber(20 + 20 * (g.bigTalent[i] or 0))
            end
        end
    end)
end

